### ISSUE TITLE
About confusion matrix

### ISSUE THREAD

**Issue by laopidu** [zhangce01/HiKER-SGG#9]
Hello,in the hikersgg_predcls_test.ipynp,the confusion matrix 'conf/conf_mat_updated_8.npy',seemed haven't mentioned in your setup.
Npy file I only have conf_mat_freq_train.npy

**Comment by zhangce01** [comment]
In `hikersgg_sgcls_train.ipynb`, we update and save the confusion matrix in the training process. Please refer to Section 3.7 in the paper for more details.

**Comment by laopidu** [comment]
With sincere gratitude!


```
# Also load the corresponding confusion matrix
conf_matrix = np.load('/home/ce/data/vg/conf/conf_mat_updated_8.npy') # Remember to change to the path of the confusion matrix
np.save('/home/ce/data/vg/conf_mat_updated.npy', conf_matrix)



 if (epoch + 1) % 3 == 0:
        print('Evaluating new confusion matrix...')
        conf_matrix = train_evaluate()
        conf_matrix[0, :] = 0.0
        conf_matrix[:, 0] = 0.0
        conf_matrix[0, 0] = 1.0
        conf_matrix = conf_matrix / (conf_matrix.sum(-1)[:, None] + 1e-8)
        conf_matrix = adj_normalize(conf_matrix)
        conf_matrix_list.append(conf_matrix)

        conf_matrix_old = np.load('/home/ce/data/vg/conf_mat_updated.npy')
        conf_matrix_new = conf_matrix_old * alpha + conf_matrix * (1 - alpha)
        np.save('/home/ce/data/vg/conf_mat_updated.npy', conf_matrix_new)
        np.save('/home/ce/data/vg/conf/conf_mat_updated_{}.npy'.format(epoch), conf_matrix_new)
```

1. In hikersgg_sgcls_train.ipynb, no statement defining 'adj_normalize' was found.
2. From the article Neural Motifs: Scene Graph Parsing with Global Context and /rowanz/neural-motifs/, I only found mapping matrix, but no information and files related to confusion matrix.
3. Through the link, I can't find the corresponding vgrel-10\vgrel-11 files. I can only find vg-24.tar and download it.
4. The code shows that I need to load conf_mat_updated_8.npy first, although conf_mat_updated_{}.npy will be generated later.
5. When I replace vg-24.tar with the directory where the model is required, and replace conf_mat_freq_train.npy with the directory where conf_mat_updated_8.npy is required, running hikersgg_sgcls_train.py will result in Assertion error.
```
  File "/home/lg/HiKER-SGG-main/dataloaders/visual_genome.py", line 379, in load_image_filenames
    assert len(fns) == 108073
```

**Comment by zhangce01** [comment]
1. `adj_normalize` is defined in [lib/my_util.py](https://github.com/zhangce01/HiKER-SGG/blob/4bdb5f9ee2896597d9d598962c3883e3542aa127/lib/my_util.py#L61).
2. Please refer to [this issue](https://github.com/zhangce01/HiKER-SGG/issues/2#issuecomment-2066748702) to download `conf_mat_freq_train.npy`.
3. As mentioned in `README.md`, `vgrel-11` is from [https://github.com/alirezazareian/gbnet](https://github.com/alirezazareian/gbnet). 
4. In the training process, please load `conf_mat_freq_train.npy` as initialization first.
5. I haven't encountered this issue before. You might want to check your dataset downloading process, as there are only 108,077 images in the dataset.

**Comment by laopidu** [comment]
1. Solved by adding from lib.my_util import adj_normalize.
2. I replaced the file name ‘conf_mat_updated_8.npy’ with ‘conf_mat_freq_train’ in the code, and the same file.
3. The code base is the same as the link pointed to in the issue, and the hyperlinks to the entire code base include: VG-images, VG metadata, vg-24.tar, whl, /checkpoints/(kern_predcls/exp, kern_sgcls/exp, vgdet/vg-24), caches/exp and other people's repositories. No vgrel-10 or vgrel-11 files.
4. Just do the second point.
5. I don't know if it is caused by different parameters of the pre-trained model. This needs to be known after downloading vgrel-10.

**Comment by zhangce01** [comment]
3. GB-Net provides the pre-trained models in [this link](https://www.dropbox.com/scl/fo/lfu0gvqsisekpgfze1uor/ABk2Q2QU_POjaW3ezhsa6X4/kern_predcls/exp_045_rep?dl=0&rlkey=cwldvfa0p24iohkb5638k8h0s&subfolder_nav_tracking=1).

**Comment by laopidu** [comment]
The pre-trained model has been placed in the set path.

I re-downloaded VG_100K and image_data.json, but the error still occurs.
hikersgg_sgcls_train.py
```
~~~~~~~~ Hyperparameters used: ~~~~~~~
ckpt : checkpoints/kern_predcls/hikersgg_predcls_train/vgrel-10.tar
save_dir : checkpoints/kern_sgcls/hikersgg_sgcls_train
num_gpus : 1
num_workers : 8
lr : 1e-05
batch_size : 3
val_size : 5000
l2 : 0.0001
adamwd : 0.0
clip : 5.0
print_interval : 2500
mode : sgcls
cache : 
adam : True
test : False
test_n : False
num_epochs : 50
use_resnet : False
use_proposals : False
pooling_dim : 4096
use_ggnn_obj : False
ggnn_obj_time_step_num : 3
ggnn_obj_hidden_dim : 512
ggnn_obj_output_dim : 512
use_obj_knowledge : False
obj_knowledge : 
use_ggnn_rel : False
ggnn_rel_time_step_num : 3
ggnn_rel_hidden_dim : 512
ggnn_rel_output_dim : 512
use_rel_knowledge : False
rel_knowledge : 
tb_log_dir : summaries/kern_sgcls/hikersgg_sgcls_train
save_rel_recall : 
Dataloader NOT using BPL
Traceback (most recent call last):
  File "/home/lg/HiKER-SGG-main/ipynb/train_sgcls/hikersgg_sgcls_train.py", line 109, in <module>
    train_full, val, test = VG.splits(num_val_im=conf.val_size, filter_duplicate_rels=True,
  File "/home/lg/HiKER-SGG-main/dataloaders/visual_genome.py", line 155, in splits
    train = cls('train', *args, **kwargs)
  File "/home/lg/HiKER-SGG-main/dataloaders/visual_genome.py", line 81, in __init__
    self.filenames = load_image_filenames(image_file)
  File "/home/lg/HiKER-SGG-main/dataloaders/visual_genome.py", line 379, in load_image_filenames
    assert len(fns) == 108073
AssertionError
```
My images folder has 64347 items and images2 has 43904 items.
I will try to run it with jypyter notebook tomorrow if there are no obvious errors in these information.

**Comment by zhangce01** [comment]
Please check this code in `visual_genome.py`:
```
def load_image_filenames(image_file, image_dir=VG_IMAGES):
    """
    Loads the image filenames from visual genome from the JSON file that contains them.
    This matches the preprocessing in scene-graph-TF-release/data_tools/vg_to_imdb.py.
    :param image_file: JSON file. Elements contain the param "image_id".
    :param image_dir: directory where the VisualGenome images are located
    :return: List of filenames corresponding to the good images
    """
    with open(image_file, 'r') as f:
        im_data = json_load(f)

    corrupted_ims = ['1592.jpg', '1722.jpg', '4616.jpg', '4617.jpg']
    fns = []
    for i, img in enumerate(im_data):
        basename = '{}.jpg'.format(img['image_id'])
        if basename in corrupted_ims:
            continue

        filename = os_path_join(image_dir, basename)
        if os_path_exists(filename):
            fns.append(filename)
    assert len(fns) == 108073
    return fns
```

We load the `image_data.json` file first, which should contain 108,077 image ids. Then we delete 4 corrupted ones to get 108,073 images. So please check your  `image_data.json` file instead of the image folder.

**Comment by laopidu** [comment]
Sincere thanks!

```
def load_image_filenames(image_file, image_dir=VG_IMAGES):
    with open(image_file, 'r') as f:
        im_data = json_load(f)

    print(f"Total images in JSON: {len(im_data)}")
    print(f"Image directory: {image_dir}")
    corrupted_ims = ['1592.jpg', '1722.jpg', '4616.jpg', '4617.jpg']
    fns = []
    skipped_corrupted = 0
    skipped_not_exists = 0

    for i, img in enumerate(im_data):
        basename = '{}.jpg'.format(img['image_id'])
        if basename in corrupted_ims:
            skipped_corrupted += 1
            continue

        filename = os_path_join(image_dir, basename)
        if os_path_exists(filename):
            fns.append(filename)
        else:
            skipped_not_exists += 1

    print(f"Skipped corrupted: {skipped_corrupted}")
    print(f"Skipped not exists: {skipped_not_exists}")
    print(f"Valid images found: {len(fns)}")

    try:
        assert len(fns) == 108073
    except AssertionError:
        print(f"Expected 108073 images, but found {len(fns)}")
        raise

    return fns
```
After finding out that my directory was ok, I took another look at the setup and saw that I had not extracted the two zip files and put all the images in a single folder.

Finally, after automatically downloading vgg16-397923af.pth, my computer got stuck and I couldn't even move the mouse (start training).

```
~~~~~~~~ Hyperparameters used: ~~~~~~~
ckpt : checkpoints/kern_predcls/hikersgg_predcls_train/vgrel-10.tar
save_dir : checkpoints/kern_sgcls/hikersgg_sgcls_train
num_gpus : 1
num_workers : 8
lr : 1e-05
batch_size : 3
val_size : 5000
l2 : 0.0001
adamwd : 0.0
clip : 5.0
print_interval : 2500
mode : sgcls
cache : 
adam : True
test : False
test_n : False
num_epochs : 50
use_resnet : False
use_proposals : False
pooling_dim : 4096
use_ggnn_obj : False
ggnn_obj_time_step_num : 3
ggnn_obj_hidden_dim : 512
ggnn_obj_output_dim : 512
use_obj_knowledge : False
obj_knowledge : 
use_ggnn_rel : False
ggnn_rel_time_step_num : 3
ggnn_rel_hidden_dim : 512
ggnn_rel_output_dim : 512
use_rel_knowledge : False
rel_knowledge : 
tb_log_dir : summaries/kern_sgcls/hikersgg_sgcls_train
save_rel_recall : 
Dataloader NOT using BPL
Total images in JSON: 108077
Image directory: /home/lg/data/vg/VG_100K
Skipped corrupted: 4
Skipped not exists: 0
Valid images found: 108073
Dataloader NOT using BPL
Total images in JSON: 108077
Image directory: /home/lg/data/vg/VG_100K
Skipped corrupted: 4
Skipped not exists: 0
Valid images found: 108073
Dataloader NOT using BPL
Total images in JSON: 108077
Image directory: /home/lg/data/vg/VG_100K
Skipped corrupted: 4
Skipped not exists: 0
Valid images found: 108073
Dataloader using BPL
Total images in JSON: 108077
Image directory: /home/lg/data/vg/VG_100K
Skipped corrupted: 4
Skipped not exists: 0
Valid images found: 108073
Dataloader using BPL
Total images in JSON: 108077
Image directory: /home/lg/data/vg/VG_100K
Skipped corrupted: 4
Skipped not exists: 0
Valid images found: 108073
Dataloader using BPL
Total images in JSON: 108077
Image directory: /home/lg/data/vg/VG_100K
Skipped corrupted: 4
Skipped not exists: 0
Valid images found: 108073
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /home/lg/.cache/torch/hub/checkpoints/vgg16-397923af.pth
100%|██████████| 528M/528M [03:09<00:00, 2.93MB/s]

Process finished with exit code 137 (interrupted by signal 9:SIGKILL)
```
